### ISSUE TITLE
Hardware Support

### ISSUE THREAD

**Issue by leo60228** [laanwj/k210-sdk-stuff#5]
Is the [MAix Bit](https://www.seeedstudio.com/Sipeed-MAix-BiT-for-RISC-V-AI-IoT-1-p-2873.html) supported by the graphical examples? It seems to have very similar functionality to the Go you're using, but I'm not sure if the pinout is similar enough.

**Comment by laanwj** [comment]
it looks like the pinout for the LCD pins is slightly different (see the blue pins to the bottom right):

This is for the M1:
![pinmap](https://user-images.githubusercontent.com/126646/62327179-318bcc80-b4b0-11e9-86f2-9ef08d532151.png)

This is for the new one:
![](https://raw.githubusercontent.com/SeeedDocument/Outsourcing/master/Sipeed%20Pic/Sipeed-M1-aa.jpg)

Assuming they do use the same LCD module, it should be a matter of changing the pin assignments in `rust/k210-shared/src/board/def.rs`:
```rust
/** I/O pins for FPIOA */
#[derive(Copy, Clone)]
pub enum io {
…
    /** LCD chip select (output) */
    LCD_CS = 36,
    /** LCD reset (output) */
    LCD_RST = 37,
    /** LCD Data/Command */
    LCD_DC = 38,
    /** LCD SPI SCLK */
    LCD_WR = 39,
…
}
```

I think easiest way to know how to adopt it would be to look at the difference for the Maix-provided C samples for the boards, see what pin numbers they provide to the fpioa set function commands.

**Comment by laanwj** [comment]
Here's a detailed schematic http://dl.sipeed.com/MAIX/HDK/Maix-Bit/Maix-Bit_1.09/Maix-Bit_1.09%28Schematic%29.pdf, which seems to have the same pin numbers as Maix Go:
```
LCD_CS 36
LCD_RST 37
LCD_DC 38
LCD_WR 39
```
It mentions nowhere what exact kind of LCD is used though. Whether this "8bit MCU LCD" is the same ST7789V. As it's the same dimensions and 320×240 resolution I wouldn't be surprised if it was.

Another spec document: http://dl.sipeed.com/MAIX/HDK/Maix-Bit/Specifications/Sipeed%20Maix-BIT%20Specifications_EN%20V2.0.pdf  seems it confirms the LCD pins are unswizzled.

**Comment by leo60228** [comment]
I'm getting mine in about a week. Do you think it would be safe to just try the examples and see if they work?

**Comment by laanwj** [comment]
I don't *think* that can do anything really harmful, no. It's similar enough.

Looking at the schematic there are some components missing such as the I2C bus on io_30/io_31. So the acceleratometer/touch screen is not going to work. But only a few of the demos rely on that.

**Comment by laanwj** [comment]
Please let me know how it goes !
