### ISSUE TITLE
compiled code not working

### ISSUE THREAD

**Issue by poysh** [laanwj/k210-sdk-stuff#6]
Hey, 

I used to compile and flash your code flawlessly on MacOS, now I am on Ubuntu and I don't see anything on the display or the cmd after writing the code to the SRAM. Any way I can get more information about why its not working?

Any help is appreciated

**Comment by poysh** [comment]
Found my issue, its working again, I think I was missing the pyelftool

**Comment by laanwj** [comment]
Oh, happy to hear that that solved it, might add this to the README.
